-d C:\Users\gusta\OneDrive\Documentos\Projetos_Quartus\telinha_labirinto\impl\gwsynthesis\telinha_labirinto.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\gusta\OneDrive\Documentos\Projetos_Quartus\telinha_labirinto\src\telinha_labirinto.cst
-cfg C:\Users\gusta\OneDrive\Documentos\Projetos_Quartus\telinha_labirinto\impl\pnr\device.cfg
-bit
-tr
-ph
-sdf
-ibs
-posp
-warning_all
-timing
-cst_error
-route_maxfan 23
